// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yxwTqAAsfMp54ofT-4xgj0MgSveWWuo',
    appId: '1:114418983640:web:bb253b9bd073f4d1deedad',
    messagingSenderId: '114418983640',
    projectId: 'smartapp-bc0df',
    authDomain: 'smartapp-bc0df.firebaseapp.com',
    storageBucket: 'smartapp-bc0df.firebasestorage.app',
    measurementId: 'G-YC7V9FQ2ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA6xRBmbKAFsBS75iRohvfk9N9zUSDnlQ',
    appId: '1:114418983640:android:ecf89571a8d758e6deedad',
    messagingSenderId: '114418983640',
    projectId: 'smartapp-bc0df',
    storageBucket: 'smartapp-bc0df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TAr91VjdUjEwhaJuDYrzYp1D9_jY5Uo',
    appId: '1:114418983640:ios:0010d5603342e9c9deedad',
    messagingSenderId: '114418983640',
    projectId: 'smartapp-bc0df',
    storageBucket: 'smartapp-bc0df.firebasestorage.app',
    iosBundleId: 'elbakkouri.smartAppElbakkouri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3TAr91VjdUjEwhaJuDYrzYp1D9_jY5Uo',
    appId: '1:114418983640:ios:0010d5603342e9c9deedad',
    messagingSenderId: '114418983640',
    projectId: 'smartapp-bc0df',
    storageBucket: 'smartapp-bc0df.firebasestorage.app',
    iosBundleId: 'elbakkouri.smartAppElbakkouri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-yxwTqAAsfMp54ofT-4xgj0MgSveWWuo',
    appId: '1:114418983640:web:70ebd1701374648cdeedad',
    messagingSenderId: '114418983640',
    projectId: 'smartapp-bc0df',
    authDomain: 'smartapp-bc0df.firebaseapp.com',
    storageBucket: 'smartapp-bc0df.firebasestorage.app',
    measurementId: 'G-TB0XY7DP8V',
  );
}
